programming_languages = [
    "Python 🐍",
    "Java ☕",
    "JavaScript 💻",
    "C 📜",
    "C++ 🗃️",
    "C# #️⃣",
    "Ruby 💎",
    "Swift 🚀",
    "Objective-C 👨‍💻",
    "PHP 🐘",
    "TypeScript 📜💻",
    "HTML/CSS 🌐🎨",
    "Kotlin 🌟",
    "Go (Golang) 🏃‍♂️",
    "Rust 🦀",
    "Shell scripting languages (e.g., Bash) 🐚💻",
    "MATLAB 🧮",
    "R 📊",
    "Scala 🚀",
    "Groovy 🍇🐾",
    "Dart 🎯",
    "Lua 🌙",
    "Perl 🐪",
    "Haskell λ",
    "Julia 📊",
    "Erlang 💡",
    "Lisp 🤖",
    "Prolog 🤔",
    "Assembly languages (e.g., x86 assembly) 🖥️",
    "SQL 📊",
]
experience_levels = ['junior 👶', 'trainee 👨‍🎓', 'mid-level 👨‍💼', 'senior 👴']